from csmt.zoopt.vegans.models.unconditional.AAE import AAE
from csmt.zoopt.vegans.models.unconditional.LSGAN import LSGAN
from csmt.zoopt.vegans.models.unconditional.LRGAN import LRGAN
from csmt.zoopt.vegans.models.unconditional.EBGAN import EBGAN
from csmt.zoopt.vegans.models.unconditional.KLGAN import KLGAN
from csmt.zoopt.vegans.models.unconditional.VAEGAN import VAEGAN
from csmt.zoopt.vegans.models.unconditional.InfoGAN import InfoGAN
from csmt.zoopt.vegans.models.unconditional.BicycleGAN import BicycleGAN
from csmt.zoopt.vegans.models.unconditional.VanillaGAN import VanillaGAN
from csmt.zoopt.vegans.models.unconditional.VanillaVAE import VanillaVAE
from csmt.zoopt.vegans.models.unconditional.WassersteinGAN import WassersteinGAN
from csmt.zoopt.vegans.models.unconditional.WassersteinGANGP import WassersteinGANGP

from csmt.zoopt.vegans.models.conditional.ConditionalAAE import ConditionalAAE
from csmt.zoopt.vegans.models.conditional.ConditionalLSGAN import ConditionalLSGAN
from csmt.zoopt.vegans.models.conditional.ConditionalLRGAN import ConditionalLRGAN
from csmt.zoopt.vegans.models.conditional.ConditionalEBGAN import ConditionalEBGAN
from csmt.zoopt.vegans.models.conditional.ConditionalKLGAN import ConditionalKLGAN
from csmt.zoopt.vegans.models.conditional.ConditionalVAEGAN import ConditionalVAEGAN
from csmt.zoopt.vegans.models.conditional.ConditionalInfoGAN import ConditionalInfoGAN
from csmt.zoopt.vegans.models.conditional.ConditionalPix2Pix import ConditionalPix2Pix
from csmt.zoopt.vegans.models.conditional.ConditionalCycleGAN import ConditionalCycleGAN
from csmt.zoopt.vegans.models.conditional.ConditionalBicycleGAN import ConditionalBicycleGAN
from csmt.zoopt.vegans.models.conditional.ConditionalVanillaGAN import ConditionalVanillaGAN
from csmt.zoopt.vegans.models.conditional.ConditionalVanillaVAE import ConditionalVanillaVAE
from csmt.zoopt.vegans.models.conditional.ConditionalWassersteinGAN import ConditionalWassersteinGAN
from csmt.zoopt.vegans.models.conditional.ConditionalWassersteinGANGP import ConditionalWassersteinGANGP