wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.12
    start_time: 1664615652.877316
    t:
      1:
      - 1
      - 4
      - 5
      - 6
      - 15
      - 53
      - 55
      3:
      - 23
      4: 3.6.12
      5: 0.13.3
      8:
      - 5
